# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e2d724bbaca52cde96b4700e1366f8a54dac680c1514f4e44c298db012e146d7a7c4e26c8c160e9b12a7aba1aed90ae9f2a0e651780bb88bae08f60c6493b8d

test:
  secret_key_base: 981d90964d7819afa27b6528e0177cb65a09403db6e2e915d93c46ebf9457350488ece777b1cf879aed236b5735e503cc656bd7350650c523f4204369f400333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
